### ISSUE TITLE
Bills Change Logic and Columns

### ISSUE THREAD

**Issue by sandipkrtya** [jariwbh/membroz-restaurant#4]
**Need to change Logic and Add Columns**

**Columns**
1. Order Type
2. Payment Status
3. Delivery Address
4. Delivery Boy

**Comment by HarshadJariwala** [comment]
Need to change Logic and Add Columns done 

![image](https://user-images.githubusercontent.com/66785452/96681471-f1ef2000-1394-11eb-88c6-da60648c518d.png)
